#[setup-gitactions] Deploy VNET

env:
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]

name: DotNetMvcARMDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      
    steps:
      
      - name: Login to Azure
        uses: Azure/login@v1.4.6
        with: 
          creds: ${{secrets.AZURE_CREDENTIALS }}
      
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Get dir
        uses: azure/CLI@v1
        with: 
          inlineScript: pwd

      - name: List content
        uses: azure/CLI@v1
        with: 
          inlineScript: ls          

      - name: Deploy ARM template
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az deployment group create \
              --resource-group rg_dotnetmvc \
              --template-file armtemplates/storageaccount.json \
              --parameters armtemplates/storageaccount.parameters.json
